config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:index, :new, :create, :destroy]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :description, presence: true, length: {minimum: 50}
  validates :question, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, presence: true
  validates :title, length: { minimum: 40 }
  validates :description, presence: true
  validates :description, length: { minimum: 150 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  # def self.find_or_create_from_omniauth(auth)
  # provider = auth.provider
  # uid = auth.uid
  #
  #   find_or_create_by(provider: provider, uid: uid) do |user|
  #     user.provider = provider
  #     user.uid = uid
  #     user.email = auth.info.email
  #     user.username = auth.info.name
  #     user.avatar_url = auth.info.image
  #   end
  # end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answers = @question.answers.order(created_at: :asc)
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:notice] = 'Answer successfully submitted!'
      redirect_to question_path(@question)
    else
      flash[:alert] = "Answer was not saved! #{@answer.errors.full_messages.join ","}."
      render :'questions/show'
    end
  end

  private
    def answer_params
      params.require(:answer).permit(
      :description
      )
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(:created_at).paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :asc)
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = "Question created!"
      redirect_to questions_path
    else
      flash[:alert] = "Question not created! #{@question.errors.full_messages.join ","}."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    #add error message
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Question saved!"
      redirect_to question_path(@question)
    else
      flash[:alert] = "Question not saved! #{@question.errors.full_messages.join ","}."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @answers = @question.answers

    if @question.destroy!
      @answers.map { |answer| answer.destroy!  }

      flash[:notice] = "Question deleted!"
    end
    redirect_to questions_path
  end


  private

  def question_params
    params.require(:question).permit(
      :title,
      :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :description, "Answer" %>:<br>
  <%= f.text_area :description %><br>
  <%= f.submit "Submit Answer" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Rescue Mission" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="container">
        <a class="logo" href="/questions">Rescue Mission</a>

      </div>
    </div>
    <% if flash.any? %>
      <div class="flash">
        <div class="container">
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </div>
      </div>
    <% end %>
    <div class="container">
   <div class="row">
     <div class="column">
       <%= yield %>
     </div>
   </div>
 </div>
  </body>
</html>

app/views/questions/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Edit Question</h1>
    <%= button_to "Delete", question_path(@question), method: :delete %>
    <br><br>
   <%= form_for(@question) do |f| %>

     <div class="field">
       <%= f.label :title %><br>
       <%= f.text_field :title %>
     </div><br />

     <div class="field">
       <%= f.label :description %><br>
       <%= f.text_area :description %>
     </div><br />

     <div class="field">
       <%= f.submit "Update" %>
     </div>

   <% end %>
  </body>
</html>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Question Queue</title>
  </head>
  <body>
    <%= link_to "New Question", new_question_path %>
    <br><br>
<<<<<<< HEAD
    <%= foundation_paginate @questions %>
=======
    <%= will_paginate @questions %>
>>>>>>> user-auth
    <br><br>
    <% @questions.each do |question| %>
    <li><%= link_to question.title, question %></li>
    <br>
    <% end %>
  </body>
</html>

app/views/questions/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Submit a New Question</h1>

   <%= form_for(@question) do |f| %>

     <div class="field">
       <%= f.label :title %><br>
       <%= f.text_field :title %>
     </div><br />

     <div class="field">
       <%= f.label :description %><br>
       <%= f.text_area :description %>
     </div><br />

     <div class="field">
       <%= f.submit "Submit Question" %>
     </div>

   <% end %>
  </body>
</html>

app/views/questions/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Question: <%= @question.id %></title>
  </head>
  <body>
    <h1><%= @question.title %></h1>
    <br><br>
    <%= link_to 'Edit Question', edit_question_path(@question) %>
    <br>
    <br>
    <%= button_to "Delete", question_path(@question), method: :delete %>
    <p>
      <h2>Description:</h2>
      <%= markdown(@question.description) %>
    </p>
    <br><br>
<%= render './answers/form' %>
    <br><br>
    <h2>Answers:</h2>
    <% @answers.each do |answer| %>
    <li>
      <%= markdown(answer.description) %>
    </li>
    <% end %>
  </body>
</html>